repos:
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.13.1
  hooks:
  - id: gitlint
- repo: https://github.com/wiedzmin/git-hooks
  rev: master
  hooks:
  - id: forbid-pushing-wip
- repo: https://github.com/pycqa/isort
    rev: 5.6.3
    hooks:
      - id: isort
        {{ if .pythonEnableBlack }}args: ["--profile", "black", "--filter-files"]{{ end }}
