# TODO: https://www.tweag.io/blog/2020-08-12-poetry2nix/
# TODO: https://github.com/nix-community/poetry2nix

default:
    @just --choose

# Build docker-compose infra
build-docker:
    docker-compose build

# Test project
test:
    echo "add actual testing command(s) here or add task(s) as needed"

# Publish source code updates
publish: test
    git push

# Enforce publishing source code updates
publish-force: test
    git push --force-with-lease

# Install "pre-commit" hooks
pre-commit-install:
    pre-commit install

# Update "pre-commit" hooks
pre-commit-update-hooks:
    pre-commit autoupdate
