publish: generate build lint
	git push

publish/force: generate build lint
	git push --force-with-lease

# TODO: https://www.tweag.io/blog/2020-08-12-poetry2nix/
# TODO: https://github.com/nix-community/poetry2nix
