{ ... }: {
  imports = [
    ./appearance
    ./browsers/chromium
    ./browsers/firefox
    ./browsers/firefox/impl.nix
    ./browsers/next
    ./browsers/qutebrowser
    ./ccpp
    ./content
    ./dbms
    ./dev
    ./ebook
    ./emacs
    ./email
    ./email/mbsync.nix
    ./git
    ./golang
    ./housekeeping
    ./knowledgebase
    ./navigation
    ./networking
    ./packaging
    ./paperworks
    ./pim
    ./powermanagement
    ./python
    ./security
    ./shell
    ./shell/misc/tmux.nix
    ./sound
    ./video
    ./virt
    ./wm
    ./wm/i3
    ./wm/stumpwm
    ./wm/xmonad
    ./xinput
  ];
}
