{ ... }: {
  imports = [
    ./attributes.nix

    ./appearance/colorschemes/zenburn
    ./appearance/emacs
    ./appearance/fonts
    ./appearance/gtk
    ./appearance/wallpaper
    ./appearance/xresources
    ./browsers/chromium
    ./browsers/firefox
    ./browsers/firefox/impl.nix
    ./browsers/nyxt
    ./browsers/qutebrowser
    ./content/ebooks
    ./content/media
    ./content/misc
    ./content/screenshots
    ./controlcenter
    ./dev/ccpp
    ./dev/completion
    ./dev/dbms/misc
    ./dev/dbms/mysql
    ./dev/dbms/pgsql
    ./dev/dbms/sqlite
    ./dev/direnv
    ./dev/editorconfig
    ./dev/frontend
    ./dev/git/autofetch
    ./dev/git/autopush
    ./dev/git/batch
    ./dev/git/core
    ./dev/git/devenv
    ./dev/git/forges
    ./dev/git/misc
    ./dev/git/navigation
    ./dev/git/savewip
    ./dev/golang
    ./dev/misc
    ./dev/ml
    ./dev/navigation/codesearch
    ./dev/navigation/projects
    ./dev/python
    ./dev/timetracking
    ./emacs/core
    ./emacs/edit
    ./emacs/history
    ./emacs/misc
    ./emacs/navigation
    ./email
    ./email/mbsync.nix
    ./gc
    ./knowledgebase
    ./navigation
    ./networking/hosts
    ./networking/messengers
    ./networking/nmconnections
    ./networking/ssh
    ./networking/vpn
    ./networking/wireless
    ./packaging
    ./paperworks
    ./pim
    ./security
    ./shell
    ./shell/misc/tmux.nix
    ./virt
    ./wm
    ./wm/i3
    ./wm/stumpwm
    ./wm/xmonad
    ./workstation/input/core
    ./workstation/input/mouse
    ./workstation/input/xkeysnail
    ./workstation/lockscreen
    ./workstation/performance
    ./workstation/power/battery
    ./workstation/power/mgmt
    ./workstation/randr
    ./workstation/sound
    ./workstation/systemtraits
    ./workstation/video/backlight
    ./workstation/video/opengl
    ./workstation/video/transparency
  ];
}
