# https://taskfile.dev

version: '3'

includes:
  laptoptop: ./machines/laptoptop
  momcat: ./machines/momcat

tasks:
  clean:
    desc: Remove system build local output
    cmds:
      - unlink ./result
    # silent: true
