LP_PS1="${LP_PS1_PREFIX}${LP_TIME}${LP_JOBS}"
LP_PS1="${LP_PS1}${LP_BRACKET_OPEN}${LP_USER}${LP_PERM}"
LP_PS1="${LP_PS1}${LP_PWD}${LP_BRACKET_CLOSE}"
LP_PS1="${LP_PS1}${LP_VCS}"
LP_PS1="${LP_PS1}${LP_RUNTIME}${LP_ERR}${LP_MARK_PREFIX}${LP_MARK}${LP_PS1_POSTFIX}"

LP_TITLE="$(_lp_title "$LP_PS1")"
LP_PS1="${LP_TITLE}${LP_PS1}"
