# https://taskfile.dev

version: '3'

vars:
  MACHINE: momcat

tasks:
  build:
    desc: Build "momcat" flake
    cmds:
      - nixos-rebuild build --flake ".#momcat"

  build:debug:
    desc: Build "momcat" flake with debug output
    cmds:
      - nixos-rebuild build --flake ".#momcat" --show-trace

  switch:
    desc: Build + switch "momcat" flake
    cmds:
      - sudo nixos-rebuild switch --flake ".#momcat"

  switch:no-net:
    desc: Build + switch "momcat" flake without network access
    cmds:
      - sudo nixos-rebuild switch --flake ".#momcat" --option binary-caches ''
