# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/gdamore/encoding";
    fetch = {
      type = "git";
      url = "https://github.com/gdamore/encoding";
      rev = "6289cdc94c00ac4aa177771c5fce7af2f96b626d";
      sha256 = "1vmm5zll92i2fm4ajqx0gyx0p9j36496x5nabi3y0x7h0inv0pk9";
    };
  }
  {
    goPackagePath = "github.com/gdamore/tcell";
    fetch = {
      type = "git";
      url = "https://github.com/gdamore/tcell";
      rev = "dcf1bb30770eb1158b67005e1e472de6d74f055d";
      sha256 = "09cxmsmq889d1nqwfl7smd2kslxdpq5dngvkjzgk9rrq00n3ds2p";
    };
  }
  {
    goPackagePath = "github.com/go-redis/redis";
    fetch = {
      type = "git";
      url = "https://github.com/go-redis/redis";
      rev = "97e6ed817821d91977b51fdec185ca2dbb917fa6";
      sha256 = "1ilp3yalg9h2zaz8mjlqdx5a0cglk8f3x3hhhf69qc59han4hqsw";
    };
  }
  {
    goPackagePath = "github.com/lucasb-eyer/go-colorful";
    fetch = {
      type = "git";
      url = "https://github.com/lucasb-eyer/go-colorful";
      rev = "30298f24079860c4dee452fdef6519b362a4a026";
      sha256 = "0fig06880bvk1l92j4127v4x9sar4ds7ga8959gxxghb2w70b7l2";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-runewidth";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-runewidth";
      rev = "703b5e6b11ae25aeb2af9ebb5d5fdf8fa2575211";
      sha256 = "0znpyz71gajx3g0j2zp63nhjj2c07g16885vxv4ykwnrfmzbgk4w";
    };
  }
  {
    goPackagePath = "github.com/mylxsw/go-toolkit";
    fetch = {
      type = "git";
      url = "https://github.com/mylxsw/go-toolkit";
      rev = "156f308c481fb5c11544e9bf2ed502e42f52189c";
      sha256 = "1da53s0n0mvxsjabafwpphvhrh1031m2h845a4qb622plk08m15f";
    };
  }
  {
    goPackagePath = "github.com/rivo/tview";
    fetch = {
      type = "git";
      url = "https://github.com/rivo/tview";
      rev = "90b4da1bd64ceee13d2e7d782b315b819190f7bf";
      sha256 = "1faibg47prgpisb15jgnqdrzmv6mc9rwv3qf97yljkc1bg511j7h";
    };
  }
  {
    goPackagePath = "github.com/rivo/uniseg";
    fetch = {
      type = "git";
      url = "https://github.com/rivo/uniseg";
      rev = "f699dde9c340bcc39b69a4c67369832af73ec72e";
      sha256 = "016zylq9i7i5dphi67p4rip21y3gjp8x567q1klh46l8plb80wbb";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "342b2e1fbaa52c93f31447ad2c6abc048c63e475";
      sha256 = "0flv9idw0jm5nm8lx25xqanbkqgfiym6619w575p7nrdh0riqwqh";
    };
  }
]
