#!/usr/bin/env python
import os
from rofi import Rofi

MACHINES_CONFIG_PATH = "/etc/nixos/machines"

r = Rofi()
configs = os.listdir(MACHINES_CONFIG_PATH)
index, keypressed = r.select('config', [config[:-4] for config in configs])
if keypressed == 0:
    os.system('sudo nixos-rebuild -I nixos-config="{0}/{1}" build-vm'.format(
        MACHINES_CONFIG_PATH, configs[index[0]]))
