#!/usr/bin/env python
import os
import dmenu

MACHINES_CONFIG_PATH = "/etc/nixos/machines"

config_entries = os.listdir(MACHINES_CONFIG_PATH)
configs = { k: v for (k, v) in zip([entry[:-4] if entry.endswith("nix") else entry for entry in config_entries], config_entries)}
result = dmenu.show(configs.keys(), prompt='config', lines=5)
if result:
    # TODO: migrate to update system after implementing (VM) builds there
    os.system('sudo nixos-rebuild -I nixos-config="{0}/{1}" build'.format(
        MACHINES_CONFIG_PATH, configs[result]))
