#!/usr/bin/env python
import os
import subprocess
import sys

import dmenu

services = []

system_units_task = subprocess.Popen("systemctl list-unit-files", shell=True, stdout=subprocess.PIPE)
services.extend(["{0} [system]".format(unit.split()[0].split(".")[0])
                 for unit in system_units_task.stdout.read().decode().split("\n")[1:-3]
                 if unit.split()[0].endswith("service")])
assert system_units_task.wait() == 0

user_units_task = subprocess.Popen("systemctl --user list-unit-files", shell=True, stdout=subprocess.PIPE)
services.extend(["{0} [user]".format(unit.split()[0].split(".")[0])
                 for unit in user_units_task.stdout.read().decode().split("\n")[1:-3]
                 if unit.split()[0].endswith("service")])
assert system_units_task.wait() == 0

journal = dmenu.show(sorted(list(dict.fromkeys(services))), prompt='journal for', lines=30)
if not journal:
    sys.exit(1)
os.system('tmux new-window "journalctl {0}-u {1}"'.format("--user " if "user" in journal else "", journal.split()[0]))
