#!/usr/bin/env python
import os
import sys

import dmenu


users = [
    "root",
    "alex3rd", # FIXME: parameterize back again
    "octocat"
]

hosts = []
with open("/etc/hosts", "r") as hostsfile:
    hosts = sorted(list(dict.fromkeys([entry.split()[1] for entry in hostsfile.read().split("\n") if len(entry)])))

user = dmenu.show(sorted(users), prompt='user', lines=5)
if not user:
    sys.exit(1)
host = dmenu.show(sorted(hosts), prompt='host', lines=20)
if not host:
    sys.exit(1)
os.system('tmux new-window "et {0}@{1}"'.format(user, host))
