#!/usr/bin/env bash

tmux has-session -t 'work' 2>/dev/null
if [ "$?" -eq 1 ] ; then
    tmux new-session -d -s 'work' -d 'mc'
fi
tmux has-session -t 'housekeeping' 2>/dev/null
if [ "$?" -eq 1 ] ; then
    tmux new-session -d -s 'housekeeping'
fi

tmux attach -t housekeeping

# TODO: implement https://gist.github.com/algesten/b1dae6873f8dcfec87c7ea8502cff8ed
