# https://taskfile.dev

version: '3'

tasks:
  build:
    desc: Build "laptoptop" flake
    cmds:
      - nixos-rebuild build --flake ".#laptoptop"

  build:debug:
    desc: Build "laptoptop" flake with debug output
    cmds:
      - nixos-rebuild build --flake ".#laptoptop" --show-trace

  build:no-net:
    desc: Build "laptoptop" flake without network access
    cmds:
      - nixos-rebuild build --flake ".#laptoptop" --option binary-caches ''

  switch:
    desc: Build + switch "laptoptop" flake
    cmds:
      - sudo nixos-rebuild switch --flake ".#laptoptop"
    silent: true

  switch:no-net:
    desc: Build + switch "laptoptop" flake without network access
    cmds:
      - sudo nixos-rebuild switch --flake ".#laptoptop" --option binary-caches ''
