#!/bin/sh
# Called by "git push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.

src_stop_words=(
   ipdb
   wdb
);

commit_stop_words=(
   [wip]
   [WIP]
)

IS_CLEAN=true

for i in "${src_stop_words[@]}"
do
    RESULTS=$(git grep -l "$i");
    if [[ ! -z "$RESULTS" ]]; then
        IS_CLEAN=false;
        echo "Found $i in file:\n$RESULTS\n";
    fi
done

for i in "${commit_stop_words[@]}"
do
    RESULTS=$(git shortlog "@{u}.." | grep "$i");
    if [[ ! -z "$RESULTS" ]]; then
        IS_CLEAN=false;
        echo "Found '$i' in commits:\n$RESULTS\n";
    fi
done

if [[ "$IS_CLEAN" = false ]]; then
    exit 1;
fi
