# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
self: super: {

  promoter = super.buildGoPackage rec {
    name = "promoter-unstable-${version}";
    version = "2019-03-17";
    rev = "4c70fc18ecffa8ce4b8d4356e27decf8476cf7ef";

    goPackagePath = "github.com/vbaksa/promoter";

    src = super.fetchgit {
      inherit rev;
      url = "https://github.com/vbaksa/promoter";
      sha256 = "0wnw6nr8yc17ik72v14q8shax7vw6vhmgi0z9n3zp4zvw0gvj7rv";
    };

    goDeps = ./deps.nix;

    # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
    meta = {};
  };

}
